name: Push to Luarocks

on:
  push:
    tags:
      - '*'
  release:
    types:
      - created
  pull_request: # Makes sure the luarocks package can build on PR
  workflow_dispatch: # Allow manual trigger (e.g. if a tagged build failed)

jobs:
  luarocks-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to count the commits
      - name: Get Version
        run: echo "LUAROCKS_VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: ${{ env.LUAROCKS_VERSION }}
          dependencies: |
            plenary.nvim
            nui.nvim
            reactivex
          labels: |
            neovim
          summary: "Docker management right inside Neovim!"
